openapi: 3.2.0
info:
  title: farmer V2.2/instance/{namespace}/env Vars API
  version: v1
tags:
- name: v2.2/instance/{namespace}/env_vars
paths:
  /v2.2/instance/{instance}/env_vars/additional_apps/{app_id}/{env_var}/:
    delete:
      parameters:
      - in: path
        name: instance
        required: true
        type: string
      - in: path
        name: app_id
        required: true
        type: string
      - in: path
        name: env_var
        required: true
        type: string
      responses:
        '200':
          content: {}
          description: Success
        '404':
          description: Environment variable variable doesn't exist
        '500':
          description: Exception occurred
      summary: Manage Additional App instance's environmental variables
      tags:
      - v2.2/instance/{namespace}/env_vars
      operationId: deleteV22InstanceByInstanceEnvVarsAdditionalAppsByAppIdByEnvVar
      x-operation-id-source: derived
  /v2.2/instance/{instance}/env_vars/datadog/{env_var}:
    delete:
      parameters:
      - in: path
        name: instance
        required: true
        type: string
      - in: path
        name: env_var
        required: true
        type: string
      responses:
        '200':
          content: {}
          description: Success
        '404':
          description: Environment variable variable doesn't exist
        '500':
          description: Exception occurred
      summary: Manage Datadog instance's environmental variables
      tags:
      - v2.2/instance/{namespace}/env_vars
      operationId: deleteV22InstanceByInstanceEnvVarsDatadogByEnvVar
      x-operation-id-source: derived
  /v2.2/instance/{instance}/env_vars/vsf/{env_var}:
    delete:
      parameters:
      - in: path
        name: instance
        required: true
        type: string
      - in: path
        name: env_var
        required: true
        type: string
      responses:
        '200':
          content: {}
          description: Success
        '404':
          description: Environment variable variable doesn't exist
        '500':
          description: Exception occurred
      summary: Manage vsf instance's environmental variables
      tags:
      - v2.2/instance/{namespace}/env_vars
      operationId: deleteV22InstanceByInstanceEnvVarsVsfByEnvVar
      x-operation-id-source: derived
  /v2.2/instance/{instance}/env_vars/vsf_api/{env_var}:
    delete:
      parameters:
      - in: path
        name: instance
        required: true
        type: string
      - in: path
        name: env_var
        required: true
        type: string
      responses:
        '200':
          content: {}
          description: Success
        '404':
          description: Environment variable variable doesn't exist
        '500':
          description: Exception occurred
      summary: Manage vsf api instance's environmental variables
      tags:
      - v2.2/instance/{namespace}/env_vars
      operationId: deleteV22InstanceByInstanceEnvVarsVsfApiByEnvVar
      x-operation-id-source: derived
