openapi: 3.2.0
info:
  title: farmer Instance API
  version: v1
tags:
- name: Instance
paths:
  /instance/{namespace}:
    get:
      parameters:
      - in: path
        name: namespace
        required: true
        type: string
      responses: {}
      tags:
      - Instance
      summary: Get instance by namespace
      x-summary-source: derived
      operationId: getInstanceByNamespace
      x-operation-id-source: derived
